src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    public const CACHE_NAME = 'user_cache_';
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups({"export"})
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @var string Name
     * @ORM\Column(type="string")
     * @Groups({"export"})
     */
    private $firstName;

    /**
     * @var string Surname
     * @ORM\Column(type="string")
     * @Groups({"export"})
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=24, nullable=false)
     * @Groups({"export"})
     */
    private $registeredCode;

    /**
     * @ORM\Column(type="boolean")
     * @Groups({"export"})
     */
    private $isActive;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"export"})
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @Orm\Column(type="string", length=255, nullable=true)
     * @Groups({"export"})
     */
    private $facebookId;

    /**
     * @Orm\Column(type="string", length=255, nullable=true)
     * @Groups({"export"})
     */
    private $googleId;

    private $plainPassword = null;

    public function __toString(): string
    {
        return $this->getFirstName().' '.$this->getLastName();
    }

    public function __construct()
    {
        $this->isActive = false;
        $this->createdAt = new DateTime();
        $this->updatedAt = new DateTime();
    }

    public function getFullName()
    {
        return $this->getFirstName().' '.$this->getLastName();
    }

    public function getRole()
    {
        if (in_array('ROLE_ADMIN', $this->roles)) {
            return 'Admin';
        }

        return 'Customer';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return string
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): User
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * @return string
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): User
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getRegisteredCode()
    {
        return $this->registeredCode;
    }

    /**
     * @param mixed $registeredCode
     *
     * @return User
     */
    public function setRegisteredCode($registeredCode)
    {
        $this->registeredCode = $registeredCode;

        return $this;
    }

    /**
     * @return false
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * @param false $isActive
     *
     * @return User
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getCreatedAt(): DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTime $createdAt): User
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): DateTime
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(DateTime $updatedAt): User
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $password): void
    {
        $this->plainPassword = $password;
    }

    public function getFacebookId(): ?string
    {
        return $this->facebookId;
    }

    public function setFacebookId(?string $facebookId): self
    {
        $this->facebookId = $facebookId;

        return $this;
    }

    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(?string $googleId): self
    {
        $this->googleId = $googleId;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html data-wf-page="{% block html_wf_page %}5f607da76425033a6ca0fef2{% endblock %}" data-wf-site="{% block html_wf_site %}5f607da76425035755a0fef1{% endblock %}" class=" {% block html_class %}w-mod-js w-mod-ix{% endblock %}" lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  {% block meta %}{% endblock %}
  {% block stylesheets %}

    {{ encore_entry_script_tags('styles') }}
    <link href="{{ asset('build/css/display.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('build/css/normalize.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('build/css/webflow.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('build/css/ecommtalks-academy.webflow.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('build/css/custom.css') }}" rel="stylesheet" type="text/css">
  {% endblock %}
  <style>

  </style>
  {% block additional_styles %}{% endblock %}
  <!-- [if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script>
  <![endif] -->
  <script type="text/javascript">!function (o, c) {
          var n = c.documentElement, t = " w-mod-";
          n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch")
      }(window, document);</script>

  <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('build/favicon/apple-touch-icon.png') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('build/favicon/favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('build/favicon/favicon-16x16.png') }}">
  <link rel="manifest" href="{{ asset('build/favicon/site.webmanifest') }}">
  <link rel="mask-icon" href="{{ asset('build/favicon/safari-pinned-tab.svg') }}" color="#f95144">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="theme-color" content="#ffffff">

  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TDPB5VS');</script>
  <!-- End Google Tag Manager -->

    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '730981817418925');
      fbq('track', 'PageView');
    </script>
    <noscript>
      <img
          height="1"
          width="1"
          style="display:none"
          src="https://www.facebook.com/tr?id=730981817418925&ev=PageView&noscript=1"
          alt=""
      />
    </noscript>
    <!-- End Facebook Pixel Code -->
</head>
<body>
<div class="header">
  <div class="header_container">
    <a href="{{ path('index') }}" aria-current="page" class="logo w-inline-block w--current">
      <img src="{{ asset('build/images/logo.svg') }}" loading="lazy" alt="">
    </a>
    {% if app.user %}
      <div class="d-flex margin_left_auto">
        <span class="welcome">
            Welcome,
          {% if app.user.fullName|length <= 1 %}
            {{ app.user.email }}
          {% else %}
            {{ app.user.fullName }}
          {% endif %}
        </span>
        <a href="{{ path('app_logout') }}">Logout</a>
      </div>
    {% endif %}
    <a data-w-id="311c2e2b-a690-654c-936a-b5860549c9f9" href="#" class="menu w-inline-block">
      <img src="{{ asset('build/images/menu_icon.svg') }}" loading="lazy" height="" alt="" class="menu_icon">
      <img
          src="{{ asset('build/images/menu_icon_close.svg') }}" loading="lazy" height="" alt=""
          class="menu_icon_close">
      <div class="menu_circle"></div>
    </a>
  </div>
</div>
<div class="nav">
  <a href="{{ path('index_courses') }}" class="nav_link w-inline-block">
    <div>Courses</div>
  </a>
  <a href="{{ path('index_speakers') }}" class="nav_link w-inline-block">
    <div>Speakers</div>
  </a>
  <a href="{{ path('information', { slug: 'about-academy' }) }}" class="nav_link w-inline-block">
    <div>About</div>
  </a>
  {% if app.user %}
    <a href="{{ path('app_logout') }}" class="nav_link w-inline-block">
      <div>Logout</div>
    </a>
  {% endif %}
</div>

{% block content %}{% endblock %}


{% if app.request.attributes.get('_route') in ['index', 'app_login', 'app_register'] %}
  {% include 'additions/subscribe_section.html.twig' %}
{% endif %}

{% include 'additions/sponsor.html.twig' %}
<div class="footer">
  <div class="container">
    <div class="div-block">
      <div id="w-node-399565929a4c-65929a49">
        <a data-w-id="a5d8f1f9-9b18-ce0b-f038-399565929a4d" href="https://www.facebook.com/ecommtalks/"
           target="_blank" class="btn padding-right_2 w-inline-block">
          <div class="btn_container">
            <img src="{{ asset('build/images/facebook_icon.svg') }}" loading="lazy" alt="">
            <div class="btn_circle"></div>
          </div>
        </a>
        <a data-w-id="a5d8f1f9-9b18-ce0b-f038-399565929a51" href="https://www.instagram.com/ecommtalks/"
           target="_blank" class="btn w-inline-block">
          <div class="btn_container">
            <img src="{{ asset('build/images/instagram_icon.svg') }}" loading="lazy" alt="">
            <div class="btn_circle"></div>
          </div>
        </a>
      </div>
      <div id="w-node-399565929a55-65929a49">
        <a href="{{ path('index_courses') }}" class="footer_link w-inline-block">
          <div>Courses</div>
        </a>
        <a href="{{ path('index_speakers') }}" class="footer_link w-inline-block">
          <div>Speakers</div>
        </a>
        <a href="{{ path('information', { slug: 'about-academy' }) }}" class="footer_link w-inline-block">
          <div>About</div>
        </a>
      </div>
    </div>
    <div class="footer_small_links">
      <div>
        <a href="{{ path('information', { slug: 'terms-and-conditions' }) }}" class="footer_link_small w-inline-block">
          <div>Terms and Conditions</div>
        </a>
        <a href="{{ path('information', { slug: 'privacy-policy' }) }}" class="footer_link_small w-inline-block">
          <div>Privacy Policy</div>
        </a>
        <a href="{{ path('information', { slug: 'cookie-policy' }) }}" class="footer_link_small w-inline-block">
          <div>Cookie Policy</div>
        </a>
      </div>
      <div>
        <a href="https://ecommpay.com/" target="_blank" class="footer_link_ecp w-inline-block">
          <div class="footer_link_ecp_text">Powered by</div>
          <img src="{{ asset('build/images/ecp_logo.svg') }}" loading="lazy" alt="" class="image-2"></a>
      </div>
    </div>
  </div>
</div>
{% block javascripts %}
  <script src="{{ asset('build/js/jquery.js') }}" type="text/javascript"></script>
  <script src="{{ asset('build/js/webflow.js') }}" type="text/javascript"></script>
  {{ encore_entry_script_tags('app') }}
{% endblock %}
{% block javascripts_jquery_required %}{% endblock %}
<!-- [if lte IE 9]>
<script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script>
<![endif] -->
<script>
    $(window).scroll(function () {
        var scroll = $(window).scrollTop();
        if (scroll >= 50) {
            $(".header_gradient").addClass("visible");
        } else {
            $(".header_gradient").removeClass("visible");
        }
    });
</script>
</body>
</html>